"""device name to unique

Revision ID: 10133a40a93f
Revises: 86faf73f737c
Create Date: 2024-01-24 18:05:59.169368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10133a40a93f'
down_revision = '86faf73f737c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['device_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
