"""add uniqie constraints

Revision ID: 25ff23c38079
Revises: 18ce43b3c42b
Create Date: 2023-10-07 17:50:25.173049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ff23c38079'
down_revision = '18ce43b3c42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['category_name'])

    with op.batch_alter_table('subscription_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['subscription_type_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
