"""add confirmed field to u_phone and u_email

Revision ID: 3db4743d5c60
Revises: a32270fd89a5
Create Date: 2023-10-08 17:43:41.477216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db4743d5c60'
down_revision = 'a32270fd89a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=False))

    with op.batch_alter_table('user_phone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_phone', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    with op.batch_alter_table('user_email', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
