"""remove device sn

Revision ID: 86faf73f737c
Revises: d64dbef4a754
Create Date: 2024-01-24 17:52:59.785448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86faf73f737c'
down_revision = 'd64dbef4a754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint('device_device_sn_key', type_='unique')
        batch_op.drop_column('device_sn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_sn', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('device_device_sn_key', ['device_sn'])

    # ### end Alembic commands ###
