"""add confirmed column to app_user

Revision ID: a32270fd89a5
Revises: 25ff23c38079
Create Date: 2023-10-08 13:36:48.840713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32270fd89a5'
down_revision = '25ff23c38079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
